name: music-segmentation-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - fastapi
  - uvicorn
  - portalocker
  - SQLAlchemy
  - psycopg2-binary
  - pydantic-settings
  - pika
  - pyyaml
  - aiofiles
  - python-multipart
  - azure-storage-blob
  - pip:
    - mir_eval