name: music-segmentation-worker-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - ffmpeg
  - numpy<1.24
  - scipy<1.9.0
  - pika
  - pip
  - pip:
    - msaf[all]
    - librosa
    - portalocker
    - azure-storage-blob
    - azure-core
    - pydantic-settings
    - mir_eval
    - --extra-index-url https://download.pytorch.org/whl/cpu
    - torch
    - torchaudio